name: It's github actions demo
run-name: ${{ github.actor }} is testing Github Actions

on:
  push:
    branches: [main]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print basic trigger info
        run: |
          echo "üéâ Triggered by: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Actor ID: ${{ github.actor_id }}"
          echo "Triggering Actor: ${{ github.triggering_actor }}"

      - name: Print ref & repo info
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Ref Type: ${{ github.ref_type }}"
          echo "Is Protected: ${{ github.ref_protected }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Owner ID: ${{ github.repository_owner_id }}"
          echo "SHA: ${{ github.sha }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base Ref: ${{ github.base_ref }}"

      - name: Print commit info
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Author Name: ${{ github.event.head_commit.author.name }}"
          echo "Author Email: ${{ github.event.head_commit.author.email }}"
          echo "Added: ${{ github.event.head_commit.added }}"
          echo "Removed: ${{ github.event.head_commit.removed }}"
          echo "Modified: ${{ github.event.head_commit.modified }}"
          echo "Commit ID: ${{ github.event.head_commit.id }}"
          echo "Commit URL: ${{ github.event.head_commit.url }}"
          echo "Tree ID: ${{ github.event.head_commit.tree_id }}"
          echo "Commit Timestamp: ${{ github.event.head_commit.timestamp }}"
          echo "Commit Distinct: ${{ github.event.head_commit.distinct }}"

      - name: Print event & server info
        run: |
          echo "Event Path: ${{ github.event_path }}"
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
          echo "GraphQL URL: ${{ github.graphql_url }}"

      - name: Print runner info
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner Arch: ${{ runner.arch }}"
          echo "Runner Temp: ${{ runner.temp }}"
          echo "Runner Tool Cache: ${{ runner.tool_cache }}"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: List files
        run: ls -la ${{ github.workspace }}

      - name: Print job status
        run: |
          echo "üçè Job Status: ${{ job.status }}"
          echo "üçè Job Container: ${{ job.container }}"
          echo "üçè Job Services: ${{ job.services }}"
