name: It's github actions demo
run-name: ${{ github.actor }} is testing Github Actions

on:
  push:
    branches: [main]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print github context info
        run: |
          echo "üîç GITHUB CONTEXT:"
          echo '${{ toJson(github) }}'

      - name: Print env context info
        run: |
          echo "üîç ENV CONTEXT:"
          echo '${{ toJson(env) }}'

      - name: Print vars context info
        run: |
          echo "üîç VARS CONTEXT:"
          echo '${{ toJson(vars) }}'

      - name: Print job context info
        run: |
          echo "üîç JOB CONTEXT:"
          echo '${{ toJson(job) }}'

      - name: Print steps context info
        run: |
          echo "üîç STEPS CONTEXT:"
          echo '${{ toJson(steps) }}'

      - name: Print runner context info
        run: |
          echo "üîç RUNNER CONTEXT:"
          echo '${{ toJson(runner) }}'

      - name: Print secrets context info
        run: |
          echo "üîç SECRETS CONTEXT:"
          echo '${{ toJson(secrets) }}'

      - name: Print strategy context info
        run: |
          echo "üîç STRATEGY CONTEXT:"
          echo '${{ toJson(strategy) }}'

      - name: Print matrix context info
        run: |
          echo "üîç MATRIX CONTEXT:"
          echo '${{ toJson(matrix) }}'

      - name: Print needs context info
        run: |
          echo "üîç NEEDS CONTEXT:"
          echo '${{ toJson(needs) }}'

      - name: Print inputs context info
        run: |
          echo "üîç INPUTS CONTEXT:"
          echo '${{ toJson(inputs) }}'

      - name: Checkout code
        uses: actions/checkout@v5

      - name: List files
        run: ls -la ${{ github.workspace }}
