name: It's github actions demo
run-name: ${{ github.actor }} is testing Github Actions

on:
  push:
    branches: [main]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print github context info
        run: |
          echo "üîç GITHUB CONTEXT:
          ${{ toJson(github) }}"

      - name: Print env context info
        run: |
          echo "üîç ENV CONTEXT:
          ${{ toJson(env) }}"

      - name: Print vars context info
        run: |
          echo "üîç VARS CONTEXT:
          ${{ toJson(vars) }}"

      - name: Print job context info
        run: |
          echo "üîç JOB CONTEXT:
          ${{ toJson(job) }}"

      - name: Print steps context info
        run: |
          echo "üîç STEPS CONTEXT:
          ${{ toJson(steps) }}"

      - name: Print runner context info
        run: |
          echo "üîç RUNNER CONTEXT:
          ${{ toJson(runner) }}"

      - name: Print secrets context info
        run: |
          echo "üîç SECRETS CONTEXT:
          ${{ toJson(secrets) }}"

      - name: Print strategy context info
        run: |
          echo "üîç STRATEGY CONTEXT:
          ${{ toJson(strategy) }}"

      - name: Print matrix context info
        run: |
          echo "üîç MATRIX CONTEXT:
          ${{ toJson(matrix) }}"

      - name: Print needs context info
        run: |
          echo "üîç NEEDS CONTEXT:
          ${{ toJson(needs) }}"

      - name: Print inputs context info
        run: |
          echo "üîç INPUTS CONTEXT:
          ${{ toJson(inputs) }}"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: List files
        run: ls -la ${{ github.workspace }}
